# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Chorus_setup.ui'
#
# Created: Mon Feb 16 14:32:12 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(510, 544)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(510, 544))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_pj = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_pj.sizePolicy().hasHeightForWidth())
        self.groupBox_pj.setSizePolicy(sizePolicy)
        self.groupBox_pj.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_pj.setObjectName("groupBox_pj")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_pj)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_projectdir = QtWidgets.QLineEdit(self.groupBox_pj)
        self.lineEdit_projectdir.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_projectdir.setObjectName("lineEdit_projectdir")
        self.horizontalLayout_2.addWidget(self.lineEdit_projectdir)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_setprojectdir = QtWidgets.QPushButton(self.groupBox_pj)
        self.pushButton_setprojectdir.setObjectName("pushButton_setprojectdir")
        self.horizontalLayout_2.addWidget(self.pushButton_setprojectdir)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_genomefile = QtWidgets.QLineEdit(self.groupBox_pj)
        self.lineEdit_genomefile.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_genomefile.setObjectName("lineEdit_genomefile")
        self.horizontalLayout_3.addWidget(self.lineEdit_genomefile)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pushButton_setgenomefile = QtWidgets.QPushButton(self.groupBox_pj)
        self.pushButton_setgenomefile.setObjectName("pushButton_setgenomefile")
        self.horizontalLayout_3.addWidget(self.pushButton_setgenomefile)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_inputfile = QtWidgets.QLineEdit(self.groupBox_pj)
        self.lineEdit_inputfile.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_inputfile.setObjectName("lineEdit_inputfile")
        self.horizontalLayout_5.addWidget(self.lineEdit_inputfile)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.pushButton_setinputfile = QtWidgets.QPushButton(self.groupBox_pj)
        self.pushButton_setinputfile.setObjectName("pushButton_setinputfile")
        self.horizontalLayout_5.addWidget(self.pushButton_setinputfile)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.groupBox_pj)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.pushButton_runchorus = QtWidgets.QPushButton(Form)
        self.pushButton_runchorus.setObjectName("pushButton_runchorus")
        self.horizontalLayout.addWidget(self.pushButton_runchorus)
        self.pushButton_stopchorus = QtWidgets.QPushButton(Form)
        self.pushButton_stopchorus.setObjectName("pushButton_stopchorus")
        self.horizontalLayout.addWidget(self.pushButton_stopchorus)
        self.pushButton_showadvance = QtWidgets.QPushButton(Form)
        self.pushButton_showadvance.setCheckable(True)
        self.pushButton_showadvance.setChecked(False)
        self.pushButton_showadvance.setObjectName("pushButton_showadvance")
        self.horizontalLayout.addWidget(self.pushButton_showadvance)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.groupBox_bt = QtWidgets.QGroupBox(Form)
        self.groupBox_bt.setEnabled(True)
        self.groupBox_bt.setObjectName("groupBox_bt")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_bt)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.groupBox_bt)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.lineEdit_gfserver = QtWidgets.QLineEdit(self.groupBox_bt)
        self.lineEdit_gfserver.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_gfserver.setObjectName("lineEdit_gfserver")
        self.horizontalLayout_6.addWidget(self.lineEdit_gfserver)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.pushButton_setgfserver = QtWidgets.QPushButton(self.groupBox_bt)
        self.pushButton_setgfserver.setObjectName("pushButton_setgfserver")
        self.horizontalLayout_6.addWidget(self.pushButton_setgfserver)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.groupBox_bt)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.lineEdit_gfclient = QtWidgets.QLineEdit(self.groupBox_bt)
        self.lineEdit_gfclient.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_gfclient.setObjectName("lineEdit_gfclient")
        self.horizontalLayout_7.addWidget(self.lineEdit_gfclient)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.pushButton_setgfclient = QtWidgets.QPushButton(self.groupBox_bt)
        self.pushButton_setgfclient.setObjectName("pushButton_setgfclient")
        self.horizontalLayout_7.addWidget(self.pushButton_setgfclient)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.groupBox_bt)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.spinBox_blatstepsize = QtWidgets.QSpinBox(self.groupBox_bt)
        self.spinBox_blatstepsize.setMinimum(5)
        self.spinBox_blatstepsize.setMaximum(13)
        self.spinBox_blatstepsize.setProperty("value", 5)
        self.spinBox_blatstepsize.setObjectName("spinBox_blatstepsize")
        self.horizontalLayout_9.addWidget(self.spinBox_blatstepsize)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.verticalLayout.addWidget(self.groupBox_bt)
        self.groupBox_pb = QtWidgets.QGroupBox(Form)
        self.groupBox_pb.setEnabled(True)
        self.groupBox_pb.setObjectName("groupBox_pb")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_pb)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.groupBox_pb)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.spinBox_pblength = QtWidgets.QSpinBox(self.groupBox_pb)
        self.spinBox_pblength.setMaximum(300)
        self.spinBox_pblength.setProperty("value", 45)
        self.spinBox_pblength.setObjectName("spinBox_pblength")
        self.horizontalLayout_8.addWidget(self.spinBox_pblength)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.groupBox_pb)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        self.spinBox_dtm = QtWidgets.QSpinBox(self.groupBox_pb)
        self.spinBox_dtm.setMinimum(1)
        self.spinBox_dtm.setProperty("value", 10)
        self.spinBox_dtm.setObjectName("spinBox_dtm")
        self.horizontalLayout_10.addWidget(self.spinBox_dtm)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_pb)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.spinBox_identity = QtWidgets.QSpinBox(self.groupBox_pb)
        self.spinBox_identity.setMinimum(50)
        self.spinBox_identity.setMaximum(100)
        self.spinBox_identity.setProperty("value", 75)
        self.spinBox_identity.setObjectName("spinBox_identity")
        self.horizontalLayout_4.addWidget(self.spinBox_identity)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.groupBox_pb)
        self.textEdit_information = QtWidgets.QTextEdit(Form)
        self.textEdit_information.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_information.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_information.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textEdit_information.setObjectName("textEdit_information")
        self.verticalLayout.addWidget(self.textEdit_information)
        self.verticalLayout.setStretch(0, 2)

        self.retranslateUi(Form)
        self.pushButton_showadvance.toggled['bool'].connect(self.groupBox_bt.setVisible)
        self.pushButton_showadvance.toggled['bool'].connect(self.groupBox_pb.setVisible)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.groupBox_bt.setVisible(False)
        self.groupBox_pb.setVisible(False)
        self.progressBar.setVisible(False)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Chorus Setup"))
        self.groupBox_pj.setTitle(_translate("Form", "Porject Setup"))
        self.lineEdit_projectdir.setPlaceholderText(_translate("Form", "Project Save Place"))
        self.pushButton_setprojectdir.setText(_translate("Form", "set"))
        self.lineEdit_genomefile.setPlaceholderText(_translate("Form", "Genome File (.fasta .fa .2bit)"))
        self.pushButton_setgenomefile.setText(_translate("Form", "set"))
        self.lineEdit_inputfile.setPlaceholderText(_translate("Form", "input file (.fasta .fa)"))
        self.pushButton_setinputfile.setText(_translate("Form", "set"))
        self.pushButton_runchorus.setText(_translate("Form", "run"))
        self.pushButton_stopchorus.setText(_translate("Form", "stop"))
        self.pushButton_showadvance.setText(_translate("Form", "advance"))
        self.groupBox_bt.setTitle(_translate("Form", "Blat"))
        self.label.setText(_translate("Form", "gfServer"))
        self.lineEdit_gfserver.setText(_translate("Form", "./blat/macOSX.x86_64/gfServer"))
        self.pushButton_setgfserver.setText(_translate("Form", "set"))
        self.label_2.setText(_translate("Form", "gfClient "))
        self.lineEdit_gfclient.setText(_translate("Form", "./blat/macOSX.x86_64/gfClient"))
        self.pushButton_setgfclient.setText(_translate("Form", "set"))
        self.label_3.setText(_translate("Form", "stepsize"))
        self.groupBox_pb.setTitle(_translate("Form", "Probe"))
        self.label_4.setText(_translate("Form", "Probe Length"))
        self.label_5.setText(_translate("Form", "dtm               "))
        self.label_6.setText(_translate("Form", "identity         "))
        self.textEdit_information.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.Helvetica Neue DeskInterface\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">information</p></body></html>"))

