# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChorusGUI2.ui'
#
# Created: Mon Jun 29 14:12:34 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 532)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setObjectName("toolBox")
        self.program_page = QtWidgets.QWidget()
        self.program_page.setGeometry(QtCore.QRect(0, 0, 616, 363))
        self.program_page.setObjectName("program_page")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.program_page)
        self.hboxlayout.setObjectName("hboxlayout")
        self.page_1_verticalLayout = QtWidgets.QVBoxLayout()
        self.page_1_verticalLayout.setObjectName("page_1_verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_program_AlnPath = QtWidgets.QLineEdit(self.program_page)
        self.lineEdit_program_AlnPath.setObjectName("lineEdit_program_AlnPath")
        self.gridLayout.addWidget(self.lineEdit_program_AlnPath, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.program_page)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_program_JFPath = QtWidgets.QLineEdit(self.program_page)
        self.lineEdit_program_JFPath.setObjectName("lineEdit_program_JFPath")
        self.gridLayout.addWidget(self.lineEdit_program_JFPath, 0, 1, 1, 1)
        self.pushButton_program_AlnPath = QtWidgets.QPushButton(self.program_page)
        self.pushButton_program_AlnPath.setObjectName("pushButton_program_AlnPath")
        self.gridLayout.addWidget(self.pushButton_program_AlnPath, 1, 3, 1, 1)
        self.pushButton_program_JFPath = QtWidgets.QPushButton(self.program_page)
        self.pushButton_program_JFPath.setObjectName("pushButton_program_JFPath")
        self.gridLayout.addWidget(self.pushButton_program_JFPath, 0, 3, 1, 1)
        self.label_program_JFversion = QtWidgets.QLabel(self.program_page)
        self.label_program_JFversion.setMinimumSize(QtCore.QSize(58, 0))
        self.label_program_JFversion.setMaximumSize(QtCore.QSize(58, 16777215))
        self.label_program_JFversion.setStyleSheet("color:red")
        self.label_program_JFversion.setObjectName("label_program_JFversion")
        self.gridLayout.addWidget(self.label_program_JFversion, 0, 4, 1, 1)
        self.label_program_Alnversion = QtWidgets.QLabel(self.program_page)
        self.label_program_Alnversion.setMinimumSize(QtCore.QSize(58, 0))
        self.label_program_Alnversion.setMaximumSize(QtCore.QSize(58, 16777215))
        self.label_program_Alnversion.setStyleSheet("color:red")
        self.label_program_Alnversion.setObjectName("label_program_Alnversion")
        self.gridLayout.addWidget(self.label_program_Alnversion, 1, 4, 1, 1)
        self.comboBox_program_Aln = QtWidgets.QComboBox(self.program_page)
        self.comboBox_program_Aln.setObjectName("comboBox_program_Aln")
        self.comboBox_program_Aln.addItem("")
        self.comboBox_program_Aln.addItem("")
        self.gridLayout.addWidget(self.comboBox_program_Aln, 1, 0, 1, 1)
        self.page_1_verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.page_1_verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_program_default = QtWidgets.QPushButton(self.program_page)
        self.pushButton_program_default.setObjectName("pushButton_program_default")
        self.horizontalLayout_3.addWidget(self.pushButton_program_default)
        self.pushButton_program_next = QtWidgets.QPushButton(self.program_page)
        self.pushButton_program_next.setObjectName("pushButton_program_next")
        self.horizontalLayout_3.addWidget(self.pushButton_program_next)
        self.page_1_verticalLayout.addLayout(self.horizontalLayout_3)
        self.hboxlayout.addLayout(self.page_1_verticalLayout)
        self.toolBox.addItem(self.program_page, "")
        self.parameter_page = QtWidgets.QWidget()
        self.parameter_page.setGeometry(QtCore.QRect(0, 0, 616, 366))
        self.parameter_page.setObjectName("parameter_page")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.parameter_page)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.page_2_verticalLayout = QtWidgets.QVBoxLayout()
        self.page_2_verticalLayout.setObjectName("page_2_verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.parameter_page)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 6, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.parameter_page)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 3, 1, 1, 1)
        self.lineEdit_parameter_samplefolder = QtWidgets.QLineEdit(self.parameter_page)
        self.lineEdit_parameter_samplefolder.setObjectName("lineEdit_parameter_samplefolder")
        self.gridLayout_2.addWidget(self.lineEdit_parameter_samplefolder, 2, 3, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.spinBox_parameter_threads = QtWidgets.QSpinBox(self.parameter_page)
        self.spinBox_parameter_threads.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBox_parameter_threads.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinBox_parameter_threads.setMinimum(1)
        self.spinBox_parameter_threads.setMaximum(12)
        self.spinBox_parameter_threads.setProperty("value", 4)
        self.spinBox_parameter_threads.setObjectName("spinBox_parameter_threads")
        self.horizontalLayout_4.addWidget(self.spinBox_parameter_threads)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 4, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.parameter_page)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 1, 1, 1)
        self.pushButton_parameter_samplename = QtWidgets.QPushButton(self.parameter_page)
        self.pushButton_parameter_samplename.setObjectName("pushButton_parameter_samplename")
        self.gridLayout_2.addWidget(self.pushButton_parameter_samplename, 2, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.parameter_page)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 8, 1, 1, 1)
        self.pushButton_parameter_inputfile = QtWidgets.QPushButton(self.parameter_page)
        self.pushButton_parameter_inputfile.setObjectName("pushButton_parameter_inputfile")
        self.gridLayout_2.addWidget(self.pushButton_parameter_inputfile, 1, 5, 1, 1)
        self.lineEdit_parameter_inputfile = QtWidgets.QLineEdit(self.parameter_page)
        self.lineEdit_parameter_inputfile.setObjectName("lineEdit_parameter_inputfile")
        self.gridLayout_2.addWidget(self.lineEdit_parameter_inputfile, 1, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.parameter_page)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.parameter_page)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.parameter_page)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.spinBox_parameter_homolog = QtWidgets.QSpinBox(self.parameter_page)
        self.spinBox_parameter_homolog.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBox_parameter_homolog.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinBox_parameter_homolog.setMinimum(50)
        self.spinBox_parameter_homolog.setMaximum(100)
        self.spinBox_parameter_homolog.setProperty("value", 75)
        self.spinBox_parameter_homolog.setObjectName("spinBox_parameter_homolog")
        self.horizontalLayout_6.addWidget(self.spinBox_parameter_homolog)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 6, 3, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.spinBox_parameter_pblength = QtWidgets.QSpinBox(self.parameter_page)
        self.spinBox_parameter_pblength.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBox_parameter_pblength.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinBox_parameter_pblength.setMinimum(32)
        self.spinBox_parameter_pblength.setMaximum(200)
        self.spinBox_parameter_pblength.setProperty("value", 45)
        self.spinBox_parameter_pblength.setObjectName("spinBox_parameter_pblength")
        self.horizontalLayout_5.addWidget(self.spinBox_parameter_pblength)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 5, 3, 1, 1)
        self.pushButton_parameter_threadsdefault = QtWidgets.QPushButton(self.parameter_page)
        self.pushButton_parameter_threadsdefault.setObjectName("pushButton_parameter_threadsdefault")
        self.gridLayout_2.addWidget(self.pushButton_parameter_threadsdefault, 4, 5, 1, 1)
        self.lineEdit_parameter_genomfile = QtWidgets.QLineEdit(self.parameter_page)
        self.lineEdit_parameter_genomfile.setObjectName("lineEdit_parameter_genomfile")
        self.gridLayout_2.addWidget(self.lineEdit_parameter_genomfile, 0, 3, 1, 1)
        self.pushButton_parameter_genomefile = QtWidgets.QPushButton(self.parameter_page)
        self.pushButton_parameter_genomefile.setObjectName("pushButton_parameter_genomefile")
        self.gridLayout_2.addWidget(self.pushButton_parameter_genomefile, 0, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.parameter_page)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 1, 1, 1)
        self.pushButton_parameter_homologydefault = QtWidgets.QPushButton(self.parameter_page)
        self.pushButton_parameter_homologydefault.setObjectName("pushButton_parameter_homologydefault")
        self.gridLayout_2.addWidget(self.pushButton_parameter_homologydefault, 6, 5, 1, 1)
        self.pushButton_parameter_pblength = QtWidgets.QPushButton(self.parameter_page)
        self.pushButton_parameter_pblength.setObjectName("pushButton_parameter_pblength")
        self.gridLayout_2.addWidget(self.pushButton_parameter_pblength, 5, 5, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.spinBox_parameter_dTm = QtWidgets.QSpinBox(self.parameter_page)
        self.spinBox_parameter_dTm.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBox_parameter_dTm.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinBox_parameter_dTm.setMaximum(45)
        self.spinBox_parameter_dTm.setProperty("value", 10)
        self.spinBox_parameter_dTm.setObjectName("spinBox_parameter_dTm")
        self.horizontalLayout_7.addWidget(self.spinBox_parameter_dTm)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 8, 3, 1, 1)
        self.pushButton_parameter_dtmdefault = QtWidgets.QPushButton(self.parameter_page)
        self.pushButton_parameter_dtmdefault.setObjectName("pushButton_parameter_dtmdefault")
        self.gridLayout_2.addWidget(self.pushButton_parameter_dtmdefault, 8, 5, 1, 1)
        self.lineEdit_parameter_rprimer = QtWidgets.QLineEdit(self.parameter_page)
        self.lineEdit_parameter_rprimer.setReadOnly(True)
        self.lineEdit_parameter_rprimer.setObjectName("lineEdit_parameter_rprimer")
        self.gridLayout_2.addWidget(self.lineEdit_parameter_rprimer, 3, 3, 1, 1)
        self.comboBox_parameter_rprimer = QtWidgets.QComboBox(self.parameter_page)
        self.comboBox_parameter_rprimer.setObjectName("comboBox_parameter_rprimer")
        self.comboBox_parameter_rprimer.addItem("")
        self.comboBox_parameter_rprimer.addItem("")
        self.comboBox_parameter_rprimer.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_parameter_rprimer, 3, 5, 1, 1)
        self.page_2_verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.pushButton_parameter_reset = QtWidgets.QPushButton(self.parameter_page)
        self.pushButton_parameter_reset.setObjectName("pushButton_parameter_reset")
        self.horizontalLayout_8.addWidget(self.pushButton_parameter_reset)
        self.pushButton_parameter_previous = QtWidgets.QPushButton(self.parameter_page)
        self.pushButton_parameter_previous.setObjectName("pushButton_parameter_previous")
        self.horizontalLayout_8.addWidget(self.pushButton_parameter_previous)
        self.pushButton_parameter_next = QtWidgets.QPushButton(self.parameter_page)
        self.pushButton_parameter_next.setObjectName("pushButton_parameter_next")
        self.horizontalLayout_8.addWidget(self.pushButton_parameter_next)
        self.page_2_verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2.addLayout(self.page_2_verticalLayout)
        self.toolBox.addItem(self.parameter_page, "")
        self.run_page = QtWidgets.QWidget()
        self.run_page.setGeometry(QtCore.QRect(0, 0, 616, 363))
        self.run_page.setObjectName("run_page")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.run_page)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.page_3_verticalLayout = QtWidgets.QVBoxLayout()
        self.page_3_verticalLayout.setObjectName("page_3_verticalLayout")
        self.textBrowser_run = QtWidgets.QTextBrowser(self.run_page)
        self.textBrowser_run.setEnabled(True)
        self.textBrowser_run.setObjectName("textBrowser_run")
        self.page_3_verticalLayout.addWidget(self.textBrowser_run)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.progressBar_run = QtWidgets.QProgressBar(self.run_page)
        self.progressBar_run.setProperty("value", 0)
        self.progressBar_run.setObjectName("progressBar_run")
        self.horizontalLayout_9.addWidget(self.progressBar_run)
        self.label_run_percentage = QtWidgets.QLabel(self.run_page)
        self.label_run_percentage.setObjectName("label_run_percentage")
        self.horizontalLayout_9.addWidget(self.label_run_percentage)
        self.label_10 = QtWidgets.QLabel(self.run_page)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.page_3_verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.pushButton_run_previous = QtWidgets.QPushButton(self.run_page)
        self.pushButton_run_previous.setObjectName("pushButton_run_previous")
        self.horizontalLayout_10.addWidget(self.pushButton_run_previous)
        self.pushButton_run_run = QtWidgets.QPushButton(self.run_page)
        self.pushButton_run_run.setObjectName("pushButton_run_run")
        self.horizontalLayout_10.addWidget(self.pushButton_run_run)
        self.pushButton_run_stop = QtWidgets.QPushButton(self.run_page)
        self.pushButton_run_stop.setObjectName("pushButton_run_stop")
        self.horizontalLayout_10.addWidget(self.pushButton_run_stop)
        self.page_3_verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout.addLayout(self.page_3_verticalLayout)
        self.toolBox.addItem(self.run_page, "")
        self.verticalLayout_4.addWidget(self.toolBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionHelp)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ChorusGUI"))
        self.label.setText(_translate("MainWindow", "Jellyfish Path"))
        self.pushButton_program_AlnPath.setText(_translate("MainWindow", "Set"))
        self.pushButton_program_JFPath.setText(_translate("MainWindow", "Set"))
        self.label_program_JFversion.setText(_translate("MainWindow", "Error"))
        self.label_program_Alnversion.setText(_translate("MainWindow", "Error"))
        self.comboBox_program_Aln.setItemText(0, _translate("MainWindow", "BWA Path"))
        self.comboBox_program_Aln.setItemText(1, _translate("MainWindow", "BLAT Path"))
        self.pushButton_program_default.setText(_translate("MainWindow", "Default"))
        self.pushButton_program_next.setText(_translate("MainWindow", "Next"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.program_page), _translate("MainWindow", "Program"))
        self.label_8.setText(_translate("MainWindow", "Homolog"))
        self.label_11.setText(_translate("MainWindow", "5\' Labeled R Primer"))
        self.label_4.setText(_translate("MainWindow", "Threads Number"))
        self.pushButton_parameter_samplename.setText(_translate("MainWindow", "Set"))
        self.label_9.setText(_translate("MainWindow", "dTm"))
        self.pushButton_parameter_inputfile.setText(_translate("MainWindow", "Find"))
        self.label_7.setText(_translate("MainWindow", "Probe Length"))
        self.label_3.setText(_translate("MainWindow", "Genome File"))
        self.label_6.setText(_translate("MainWindow", "Sample Folder"))
        self.pushButton_parameter_threadsdefault.setText(_translate("MainWindow", "Default"))
        self.pushButton_parameter_genomefile.setText(_translate("MainWindow", "Find"))
        self.label_5.setText(_translate("MainWindow", "Input File"))
        self.pushButton_parameter_homologydefault.setText(_translate("MainWindow", "Default"))
        self.pushButton_parameter_pblength.setText(_translate("MainWindow", "Default"))
        self.pushButton_parameter_dtmdefault.setText(_translate("MainWindow", "Default"))
        self.lineEdit_parameter_rprimer.setText(_translate("MainWindow", ""))
        self.comboBox_parameter_rprimer.setItemText(0, _translate("MainWindow", "Default"))
        self.comboBox_parameter_rprimer.setItemText(1, _translate("MainWindow", "MYcroarray"))
        self.comboBox_parameter_rprimer.setItemText(2, _translate("MainWindow", "Custom"))
        self.pushButton_parameter_reset.setText(_translate("MainWindow", "Reset"))
        self.pushButton_parameter_previous.setText(_translate("MainWindow", "Previous"))
        self.pushButton_parameter_next.setText(_translate("MainWindow", "Next"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.parameter_page), _translate("MainWindow", "Parameter"))
        self.label_run_percentage.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "%"))
        self.pushButton_run_previous.setText(_translate("MainWindow", "Previous"))
        self.pushButton_run_run.setText(_translate("MainWindow", "Run"))
        self.pushButton_run_stop.setText(_translate("MainWindow", "Stop"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.run_page), _translate("MainWindow", "Run"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

