# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newProject.ui'
#
# Created: Wed Feb  4 10:37:17 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewProject(object):
    def setupUi(self, NewProject):
        NewProject.setObjectName("NewProject")
        NewProject.resize(449, 368)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(NewProject)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(NewProject)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(NewProject)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.lineEdit_blat = QtWidgets.QLineEdit(NewProject)
        self.lineEdit_blat.setObjectName("lineEdit_blat")
        self.gridLayout.addWidget(self.lineEdit_blat, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(NewProject)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.spinBox_pblength = QtWidgets.QSpinBox(NewProject)
        self.spinBox_pblength.setMinimum(30)
        self.spinBox_pblength.setMaximum(300)
        self.spinBox_pblength.setProperty("value", 45)
        self.spinBox_pblength.setObjectName("spinBox_pblength")
        self.gridLayout.addWidget(self.spinBox_pblength, 5, 1, 1, 1)
        self.spinBox_threads = QtWidgets.QSpinBox(NewProject)
        self.spinBox_threads.setMinimum(1)
        self.spinBox_threads.setMaximum(128)
        self.spinBox_threads.setProperty("value", 2)
        self.spinBox_threads.setObjectName("spinBox_threads")
        self.gridLayout.addWidget(self.spinBox_threads, 8, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(NewProject)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(NewProject)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 8, 0, 1, 1)
        self.lineEdit_prjname = QtWidgets.QLineEdit(NewProject)
        self.lineEdit_prjname.setObjectName("lineEdit_prjname")
        self.gridLayout.addWidget(self.lineEdit_prjname, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(NewProject)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(NewProject)
        self.doubleSpinBox.setMaximum(1.0)
        self.doubleSpinBox.setSingleStep(0.05)
        self.doubleSpinBox.setProperty("value", 0.75)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 7, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(NewProject)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.lineEdit_inputfile = QtWidgets.QLineEdit(NewProject)
        self.lineEdit_inputfile.setObjectName("lineEdit_inputfile")
        self.gridLayout.addWidget(self.lineEdit_inputfile, 1, 1, 1, 1)
        self.lineEdit_genome = QtWidgets.QLineEdit(NewProject)
        self.lineEdit_genome.setObjectName("lineEdit_genome")
        self.gridLayout.addWidget(self.lineEdit_genome, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(NewProject)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.spinBox_dtm = QtWidgets.QSpinBox(NewProject)
        self.spinBox_dtm.setMinimum(1)
        self.spinBox_dtm.setProperty("value", 10)
        self.spinBox_dtm.setObjectName("spinBox_dtm")
        self.gridLayout.addWidget(self.spinBox_dtm, 6, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_close = QtWidgets.QPushButton(NewProject)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout.addWidget(self.pushButton_close)
        self.pushButton_next = QtWidgets.QPushButton(NewProject)
        self.pushButton_next.setObjectName("pushButton_next")
        self.horizontalLayout.addWidget(self.pushButton_next)
        self.gridLayout.addLayout(self.horizontalLayout, 9, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(NewProject)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.lineEdit_output = QtWidgets.QLineEdit(NewProject)
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.gridLayout.addWidget(self.lineEdit_output, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)

        self.retranslateUi(NewProject)
        QtCore.QMetaObject.connectSlotsByName(NewProject)

    def retranslateUi(self, NewProject):
        _translate = QtCore.QCoreApplication.translate
        NewProject.setWindowTitle(_translate("NewProject", "NewProject"))
        self.label_3.setText(_translate("NewProject", "BLAT path"))
        self.label_4.setText(_translate("NewProject", "Probe length"))
        self.label_5.setText(_translate("NewProject", "dtm"))
        self.label_9.setText(_translate("NewProject", "Output dir"))
        self.label_7.setText(_translate("NewProject", "Threads/CPU"))
        self.lineEdit_prjname.setText(_translate("NewProject", "Probeset"))
        self.label_6.setText(_translate("NewProject", "Identity"))
        self.label_2.setText(_translate("NewProject", "Genome file"))
        self.label.setText(_translate("NewProject", "Input file"))
        self.pushButton_close.setText(_translate("NewProject", "Close"))
        self.pushButton_next.setText(_translate("NewProject", "Next"))
        self.label_8.setText(_translate("NewProject", "Project Name"))

